
package com.amazon.webservices.awsecommerceservice._2008_10_06;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AWSECommerceServicePortType", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AWSECommerceServicePortType {


    /**
     * 
     * @param shared
     * @param information
     * @param operationRequest
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "Help", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "Help", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.Help")
    @ResponseWrapper(localName = "HelpResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.HelpResponse")
    public void help(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        HelpRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<HelpRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Information", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Information>> information);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param items
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "ItemSearch", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "ItemSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.ItemSearch")
    @ResponseWrapper(localName = "ItemSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.ItemSearchResponse")
    public void itemSearch(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        ItemSearchRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<ItemSearchRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Items", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Items>> items);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param items
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "ItemLookup", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "ItemLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.ItemLookup")
    @ResponseWrapper(localName = "ItemLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.ItemLookupResponse")
    public void itemLookup(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        ItemLookupRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<ItemLookupRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Items", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Items>> items);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param browseNodes
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "BrowseNodeLookup", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "BrowseNodeLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.BrowseNodeLookup")
    @ResponseWrapper(localName = "BrowseNodeLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.BrowseNodeLookupResponse")
    public void browseNodeLookup(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        BrowseNodeLookupRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<BrowseNodeLookupRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "BrowseNodes", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<BrowseNodes>> browseNodes);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param lists
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "ListSearch", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "ListSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.ListSearch")
    @ResponseWrapper(localName = "ListSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.ListSearchResponse")
    public void listSearch(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        ListSearchRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<ListSearchRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Lists", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Lists>> lists);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param lists
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "ListLookup", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "ListLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.ListLookup")
    @ResponseWrapper(localName = "ListLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.ListLookupResponse")
    public void listLookup(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        ListLookupRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<ListLookupRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Lists", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Lists>> lists);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param customers
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "CustomerContentSearch", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "CustomerContentSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.CustomerContentSearch")
    @ResponseWrapper(localName = "CustomerContentSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.CustomerContentSearchResponse")
    public void customerContentSearch(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        CustomerContentSearchRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<CustomerContentSearchRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Customers", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Customers>> customers);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param customers
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "CustomerContentLookup", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "CustomerContentLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.CustomerContentLookup")
    @ResponseWrapper(localName = "CustomerContentLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.CustomerContentLookupResponse")
    public void customerContentLookup(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        CustomerContentLookupRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<CustomerContentLookupRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Customers", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Customers>> customers);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param items
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "SimilarityLookup", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "SimilarityLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.SimilarityLookup")
    @ResponseWrapper(localName = "SimilarityLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.SimilarityLookupResponse")
    public void similarityLookup(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        SimilarityLookupRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<SimilarityLookupRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Items", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Items>> items);

    /**
     * 
     * @param sellers
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "SellerLookup", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "SellerLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.SellerLookup")
    @ResponseWrapper(localName = "SellerLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.SellerLookupResponse")
    public void sellerLookup(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        SellerLookupRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<SellerLookupRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Sellers", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Sellers>> sellers);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param cart
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "CartGet", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "CartGet", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.CartGet")
    @ResponseWrapper(localName = "CartGetResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.CartGetResponse")
    public void cartGet(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        CartGetRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<CartGetRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Cart", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Cart>> cart);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param cart
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "CartCreate", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "CartCreate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.CartCreate")
    @ResponseWrapper(localName = "CartCreateResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.CartCreateResponse")
    public void cartCreate(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        CartCreateRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<CartCreateRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Cart", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Cart>> cart);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param cart
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "CartAdd", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "CartAdd", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.CartAdd")
    @ResponseWrapper(localName = "CartAddResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.CartAddResponse")
    public void cartAdd(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        CartAddRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<CartAddRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Cart", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Cart>> cart);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param cart
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "CartModify", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "CartModify", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.CartModify")
    @ResponseWrapper(localName = "CartModifyResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.CartModifyResponse")
    public void cartModify(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        CartModifyRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<CartModifyRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Cart", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Cart>> cart);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param cart
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "CartClear", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "CartClear", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.CartClear")
    @ResponseWrapper(localName = "CartClearResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.CartClearResponse")
    public void cartClear(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        CartClearRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<CartClearRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Cart", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Cart>> cart);

    /**
     * 
     * @param shared
     * @param transactions
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "TransactionLookup", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "TransactionLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.TransactionLookup")
    @ResponseWrapper(localName = "TransactionLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.TransactionLookupResponse")
    public void transactionLookup(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        TransactionLookupRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<TransactionLookupRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Transactions", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Transactions>> transactions);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param sellerListings
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "SellerListingSearch", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "SellerListingSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.SellerListingSearch")
    @ResponseWrapper(localName = "SellerListingSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.SellerListingSearchResponse")
    public void sellerListingSearch(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        SellerListingSearchRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<SellerListingSearchRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "SellerListings", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<SellerListings>> sellerListings);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param sellerListings
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "SellerListingLookup", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "SellerListingLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.SellerListingLookup")
    @ResponseWrapper(localName = "SellerListingLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.SellerListingLookupResponse")
    public void sellerListingLookup(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        SellerListingLookupRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<SellerListingLookupRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "SellerListings", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<SellerListings>> sellerListings);

    /**
     * 
     * @param tags
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "TagLookup", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "TagLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.TagLookup")
    @ResponseWrapper(localName = "TagLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.TagLookupResponse")
    public void tagLookup(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        TagLookupRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<TagLookupRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "Tags", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<Tags>> tags);

    /**
     * 
     * @param shared
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param vehicleYears
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "VehicleSearch", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "VehicleSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.VehicleSearch")
    @ResponseWrapper(localName = "VehicleSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.VehicleSearchResponse")
    public void vehicleSearch(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        VehicleSearchRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<VehicleSearchRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "VehicleYears", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<VehicleYears>> vehicleYears);

    /**
     * 
     * @param shared
     * @param vehicleParts
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "VehiclePartSearch", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "VehiclePartSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.VehiclePartSearch")
    @ResponseWrapper(localName = "VehiclePartSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.VehiclePartSearchResponse")
    public void vehiclePartSearch(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        VehiclePartSearchRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<VehiclePartSearchRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "VehicleParts", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<VehicleParts>> vehicleParts);

    /**
     * 
     * @param shared
     * @param vehicleParts
     * @param operationRequest
     * @param xmlEscaping
     * @param marketplaceDomain
     * @param request
     * @param awsAccessKeyId
     * @param validate
     * @param subscriptionId
     * @param associateTag
     */
    @WebMethod(operationName = "VehiclePartLookup", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "VehiclePartLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.VehiclePartLookup")
    @ResponseWrapper(localName = "VehiclePartLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.VehiclePartLookupResponse")
    public void vehiclePartLookup(
        @WebParam(name = "MarketplaceDomain", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String marketplaceDomain,
        @WebParam(name = "AWSAccessKeyId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String awsAccessKeyId,
        @WebParam(name = "SubscriptionId", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String subscriptionId,
        @WebParam(name = "AssociateTag", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String associateTag,
        @WebParam(name = "Validate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String validate,
        @WebParam(name = "XMLEscaping", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        String xmlEscaping,
        @WebParam(name = "Shared", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        VehiclePartLookupRequest shared,
        @WebParam(name = "Request", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        List<VehiclePartLookupRequest> request,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "VehicleParts", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<List<VehicleParts>> vehicleParts);

    /**
     * 
     * @param cartCreateResponse
     * @param sellerLookupResponse
     * @param cartModifyResponse
     * @param itemSearchResponse
     * @param browseNodeLookupResponse
     * @param listLookupResponse
     * @param browseNodeLookup
     * @param tagLookup
     * @param sellerListingSearch
     * @param itemLookup
     * @param help
     * @param sellerLookup
     * @param similarityLookup
     * @param similarityLookupResponse
     * @param vehicleSearchResponse
     * @param cartCreate
     * @param vehiclePartSearch
     * @param tagLookupResponse
     * @param sellerListingLookupResponse
     * @param customerContentSearch
     * @param transactionLookupResponse
     * @param vehiclePartLookup
     * @param cartGetResponse
     * @param itemLookupResponse
     * @param operationRequest
     * @param vehiclePartSearchResponse
     * @param listSearchResponse
     * @param cartAddResponse
     * @param customerContentLookupResponse
     * @param cartModify
     * @param cartGet
     * @param sellerListingSearchResponse
     * @param vehicleSearch
     * @param helpResponse
     * @param itemSearch
     * @param customerContentSearchResponse
     * @param listSearch
     * @param sellerListingLookup
     * @param listLookup
     * @param vehiclePartLookupResponse
     * @param cartClear
     * @param cartAdd
     * @param cartClearResponse
     * @param transactionLookup
     * @param customerContentLookup
     */
    @WebMethod(operationName = "MultiOperation", action = "http://soap.amazon.com")
    @RequestWrapper(localName = "MultiOperation", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.MultiOperation")
    @ResponseWrapper(localName = "MultiOperationResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", className = "com.amazon.webservices.awsecommerceservice._2008_10_06.MultiOperationResponse")
    public void multiOperation(
        @WebParam(name = "Help", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        Help help,
        @WebParam(name = "ItemSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        ItemSearch itemSearch,
        @WebParam(name = "ItemLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        ItemLookup itemLookup,
        @WebParam(name = "ListSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        ListSearch listSearch,
        @WebParam(name = "ListLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        ListLookup listLookup,
        @WebParam(name = "CustomerContentSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        CustomerContentSearch customerContentSearch,
        @WebParam(name = "CustomerContentLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        CustomerContentLookup customerContentLookup,
        @WebParam(name = "SimilarityLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        SimilarityLookup similarityLookup,
        @WebParam(name = "SellerLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        SellerLookup sellerLookup,
        @WebParam(name = "CartGet", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        CartGet cartGet,
        @WebParam(name = "CartAdd", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        CartAdd cartAdd,
        @WebParam(name = "CartCreate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        CartCreate cartCreate,
        @WebParam(name = "CartModify", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        CartModify cartModify,
        @WebParam(name = "CartClear", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        CartClear cartClear,
        @WebParam(name = "TransactionLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        TransactionLookup transactionLookup,
        @WebParam(name = "SellerListingSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        SellerListingSearch sellerListingSearch,
        @WebParam(name = "SellerListingLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        SellerListingLookup sellerListingLookup,
        @WebParam(name = "TagLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        TagLookup tagLookup,
        @WebParam(name = "BrowseNodeLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        BrowseNodeLookup browseNodeLookup,
        @WebParam(name = "VehicleSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        VehicleSearch vehicleSearch,
        @WebParam(name = "VehiclePartSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        VehiclePartSearch vehiclePartSearch,
        @WebParam(name = "VehiclePartLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
        VehiclePartLookup vehiclePartLookup,
        @WebParam(name = "OperationRequest", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<OperationRequest> operationRequest,
        @WebParam(name = "HelpResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<HelpResponse> helpResponse,
        @WebParam(name = "ItemSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<ItemSearchResponse> itemSearchResponse,
        @WebParam(name = "ItemLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<ItemLookupResponse> itemLookupResponse,
        @WebParam(name = "ListSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<ListSearchResponse> listSearchResponse,
        @WebParam(name = "ListLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<ListLookupResponse> listLookupResponse,
        @WebParam(name = "CustomerContentSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<CustomerContentSearchResponse> customerContentSearchResponse,
        @WebParam(name = "CustomerContentLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<CustomerContentLookupResponse> customerContentLookupResponse,
        @WebParam(name = "SimilarityLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<SimilarityLookupResponse> similarityLookupResponse,
        @WebParam(name = "SellerLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<SellerLookupResponse> sellerLookupResponse,
        @WebParam(name = "CartGetResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<CartGetResponse> cartGetResponse,
        @WebParam(name = "CartAddResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<CartAddResponse> cartAddResponse,
        @WebParam(name = "CartCreateResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<CartCreateResponse> cartCreateResponse,
        @WebParam(name = "CartModifyResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<CartModifyResponse> cartModifyResponse,
        @WebParam(name = "CartClearResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<CartClearResponse> cartClearResponse,
        @WebParam(name = "TransactionLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<TransactionLookupResponse> transactionLookupResponse,
        @WebParam(name = "SellerListingSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<SellerListingSearchResponse> sellerListingSearchResponse,
        @WebParam(name = "SellerListingLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<SellerListingLookupResponse> sellerListingLookupResponse,
        @WebParam(name = "TagLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<TagLookupResponse> tagLookupResponse,
        @WebParam(name = "BrowseNodeLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<BrowseNodeLookupResponse> browseNodeLookupResponse,
        @WebParam(name = "VehicleSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<VehicleSearchResponse> vehicleSearchResponse,
        @WebParam(name = "VehiclePartSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<VehiclePartSearchResponse> vehiclePartSearchResponse,
        @WebParam(name = "VehiclePartLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", mode = WebParam.Mode.OUT)
        Holder<VehiclePartLookupResponse> vehiclePartLookupResponse);

}
